//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkelClient.WinkelServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WinkelServiceClient.IWinkelService")]
    public interface IWinkelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/Registreren", ReplyAction="http://tempuri.org/IWinkelService/RegistrerenResponse")]
        bool Registreren(string gebruikersnaam, string wachtwoord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/Registreren", ReplyAction="http://tempuri.org/IWinkelService/RegistrerenResponse")]
        System.Threading.Tasks.Task<bool> RegistrerenAsync(string gebruikersnaam, string wachtwoord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/Inloggen", ReplyAction="http://tempuri.org/IWinkelService/InloggenResponse")]
        bool Inloggen(string gebruikersnaam, string wachtwoord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/Inloggen", ReplyAction="http://tempuri.org/IWinkelService/InloggenResponse")]
        System.Threading.Tasks.Task<bool> InloggenAsync(string gebruikersnaam, string wachtwoord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/SaldoInformatie", ReplyAction="http://tempuri.org/IWinkelService/SaldoInformatieResponse")]
        double SaldoInformatie(string gebruikersnaam, string wachtwoord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/SaldoInformatie", ReplyAction="http://tempuri.org/IWinkelService/SaldoInformatieResponse")]
        System.Threading.Tasks.Task<double> SaldoInformatieAsync(string gebruikersnaam, string wachtwoord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/ProductenVerkijgen", ReplyAction="http://tempuri.org/IWinkelService/ProductenVerkijgenResponse")]
        string ProductenVerkijgen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/ProductenVerkijgen", ReplyAction="http://tempuri.org/IWinkelService/ProductenVerkijgenResponse")]
        System.Threading.Tasks.Task<string> ProductenVerkijgenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/Koop", ReplyAction="http://tempuri.org/IWinkelService/KoopResponse")]
        bool Koop(string gebruikersnaam, string wachtwoord, int productid, int aantal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/Koop", ReplyAction="http://tempuri.org/IWinkelService/KoopResponse")]
        System.Threading.Tasks.Task<bool> KoopAsync(string gebruikersnaam, string wachtwoord, int productid, int aantal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/KoopHistory", ReplyAction="http://tempuri.org/IWinkelService/KoopHistoryResponse")]
        string KoopHistory(string gebruikersnaam, string wachtwoord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWinkelService/KoopHistory", ReplyAction="http://tempuri.org/IWinkelService/KoopHistoryResponse")]
        System.Threading.Tasks.Task<string> KoopHistoryAsync(string gebruikersnaam, string wachtwoord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWinkelServiceChannel : WinkelClient.WinkelServiceClient.IWinkelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WinkelServiceClient : System.ServiceModel.ClientBase<WinkelClient.WinkelServiceClient.IWinkelService>, WinkelClient.WinkelServiceClient.IWinkelService {
        
        public WinkelServiceClient() {
        }
        
        public WinkelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WinkelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WinkelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WinkelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Registreren(string gebruikersnaam, string wachtwoord) {
            return base.Channel.Registreren(gebruikersnaam, wachtwoord);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrerenAsync(string gebruikersnaam, string wachtwoord) {
            return base.Channel.RegistrerenAsync(gebruikersnaam, wachtwoord);
        }
        
        public bool Inloggen(string gebruikersnaam, string wachtwoord) {
            return base.Channel.Inloggen(gebruikersnaam, wachtwoord);
        }
        
        public System.Threading.Tasks.Task<bool> InloggenAsync(string gebruikersnaam, string wachtwoord) {
            return base.Channel.InloggenAsync(gebruikersnaam, wachtwoord);
        }
        
        public double SaldoInformatie(string gebruikersnaam, string wachtwoord) {
            return base.Channel.SaldoInformatie(gebruikersnaam, wachtwoord);
        }
        
        public System.Threading.Tasks.Task<double> SaldoInformatieAsync(string gebruikersnaam, string wachtwoord) {
            return base.Channel.SaldoInformatieAsync(gebruikersnaam, wachtwoord);
        }
        
        public string ProductenVerkijgen() {
            return base.Channel.ProductenVerkijgen();
        }
        
        public System.Threading.Tasks.Task<string> ProductenVerkijgenAsync() {
            return base.Channel.ProductenVerkijgenAsync();
        }
        
        public bool Koop(string gebruikersnaam, string wachtwoord, int productid, int aantal) {
            return base.Channel.Koop(gebruikersnaam, wachtwoord, productid, aantal);
        }
        
        public System.Threading.Tasks.Task<bool> KoopAsync(string gebruikersnaam, string wachtwoord, int productid, int aantal) {
            return base.Channel.KoopAsync(gebruikersnaam, wachtwoord, productid, aantal);
        }
        
        public string KoopHistory(string gebruikersnaam, string wachtwoord) {
            return base.Channel.KoopHistory(gebruikersnaam, wachtwoord);
        }
        
        public System.Threading.Tasks.Task<string> KoopHistoryAsync(string gebruikersnaam, string wachtwoord) {
            return base.Channel.KoopHistoryAsync(gebruikersnaam, wachtwoord);
        }
    }
}
