//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinkelServiceLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAankoop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbAankoop()
        {
            this.AankoopRegels = new HashSet<tbAankoopRegel>();
        }
    
        public int Id { get; set; }
        public System.DateTime aankoopdatum { get; set; }
        public int Gebruiker_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbAankoopRegel> AankoopRegels { get; set; }
        public virtual tbGebruiker Gebruikers { get; set; }
    }
}
